### ISSUE TITLE
The vanish addon is loading before my vanish.

### ISSUE THREAD

**Issue by Creeperz653** [pl3xgaming/Pl3xMap#102]
[title]

**Comment by BillyGalbreath** [comment]
The problem isn't with the vanish plugin or with pl3xmap. The problem is you have another unrelated plugin installed that uses the [`provides` api (like FAWE)](https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/9431f7c18911d68b01d3ab96e785aa9fd72145f9#diff-2a7166626535331e6b5a85dcf13b199a4797f2a0f58920b81e6ed3e52d3d41efR7) in it's plugin.yml file. This feature was implemented incorrectly in Spigot back in [March of 2020](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/PluginDescriptionFile.java?until=9f2fd967a4f914b849afe6ac287e7a595c035884&untilPath=src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fplugin%2FPluginDescriptionFile.java), and sadly any plugin that uses this feature has a high risk of mangling up the load order for any and all plugins that use `softdepend`.

No one seems to want to fix this. I blame plugins that use provides knowing it's broken. The plugins that use provides blame spigot. spigot blames plugins like pl3xmap for using softdepend.

**Comment by Creeperz653** [comment]
no i dont have fawe

**Comment by BillyGalbreath** [comment]
I didn't say you did..
