### ISSUE TITLE
[FEATURE] Must Have's for Pl2xMap

### ISSUE THREAD

**Issue by Strahilchu** [pl3xgaming/Pl3xMap#111]
Right now Pl3xMap is not a lightweight alternative to DynMap it is more of a crappy alternative.

1. Pl3xMap should to have MySQL support
2. Pl3xMap should have /map quiet or /map silent interval (so it doesn't spam console)
3. Pl3xMap needs to be optimized to not use up all of the server's ram and overload it until it can't keep-up!
4. Pl3xMap should have option to select map quality
5. Pl3xMap needs option to pause and continue a render 

DynMap was rendering in 3D without using more than 10% cpu and ram while Pl3xMap completely crashed the server while rendering.
How is this lightweight?

**Comment by theomega24** [comment]
1. Doesn’t need to be added because it takes up minuscule space
2. Agreed
3. No one else is reporting any issues of this
4. There is no concept of quality in Pl3xMap, it’s all just one pixel per block
5. Agreed

**Comment by theomega24** [comment]
I lied about 3, ignore me

**Comment by Strahilchu** [comment]
> 1. Doesn’t need to be added because it takes up minuscule space
> 2. Agreed
> 3. No one else is reporting any issues of this
> 4. There is no concept of quality in Pl3xMap, it’s all just one pixel per block
> 5. Agreed

I am rendering a 40k radius world it uses up plenty of gigabytes that's why I want MySQL

I do agree with you on the quality thing I guess it's ok that it's pixel per block.

3. There's definitely performance issues that I can't figure out why are happening but it can't just be me!

**Comment by theomega24** [comment]
How many GB is "plenty of GB"

**Comment by Strahilchu** [comment]
> How many GB is "plenty of GB", also MySQL shouldn't be used for static file storage. It takes up the same amount of space pretty much.

About 20gb of disk space, I like to use MySQL with my host because it doesn't count towards my storage limit for the server.

**Comment by BillyGalbreath** [comment]
```
1. Pl3xMap should to have MySQL support
```
The maps don't take up very much space at all. My own [map](https://map.pl3x.net) is only 115MB for my world/nether/end, which is magnitudes smaller than dynmap.

If this is still a problem for you, then there are solutions that let you offload files to remote servers such as an NFS mount.

```
2. Pl3xMap should have /map quiet or /map silent interval (so it doesn't spam console)
```
We do have an interval setting in the config.yml, though it has a [bug ](https://github.com/pl3xgaming/Pl3xMap/issues/25) with multiplying the ETA incorrectly when it's not set to 1 second.

The progress is always output to the server's console instead of the player executing the command, so you will never be spammed to death with progress the way dynmap does. I highly recommend leaving it at 1 so you can get the most accurate ETA.

```
3. Pl3xMap needs to be optimized to not use up all of the server's ram and overload it until it can't keep-up!
```
It uses the RAM that's available to it in your startup flags (Xmx). Each tile needs to be stored in ram as it's being built, and the plugin will build multiple tiles at a time (1/2 the number of available cores, by default). Most of the "used" ram is just cache that will be overwritten when other things need the ram (other tiles, other plugins, etc) which will eventually be cleared by GC anyway. There is no issue here, this is simply how things work which is largely misunderstood by server owners.

```
4. Pl3xMap should have option to select map quality
```
There is a PNG quality setting in config.yml already.

```
5. Pl3xMap needs option to pause and continue a render
```
There is already a command to pause renders.
